### PR TITLE
change link style at hover

### PR DESCRIPTION
**Pull request by joy21fs**

### CODE REVIEW

**Comment by caasi** [comment]
Hi Joy,

Thank you for the PR.
I will close it instead of merge it. But you can still discuss with me.

Here are some keywords for today:
- resize event
- react-router
  - a gallery page for your products
  - a standalone page for each product
- BEM
- Monospace

You can also check [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/). It helps you improve your commit messages.

**Comment by joy21fs** [comment]
Thank you Isaac for the message and resources!
I will definitely look into them.

Best regards,
Joy

**Comment by joy21fs** [comment]
Hi Isaac,

This is Joy, the first interviewee for the Web Frontend Developer position
at Gemini Data.
I had looked back into the testing project for the online interview we had
on Thursday.
I was able to find a bug using Chrome DevTools --
as we use the array.map method to generate <li>s, we would need to provide
each generated element a unique key.
[image: image.png]
The key here is {user.type}, which if we refer back to the data from the
api.ts file the type would be either "legal" or "natural" and is not unique.
If we could change the key to {user._id} that would fix the bug.

This is so simple and definitely could be discovered within 5 minutes if I
haven't focused too much on the different syntax TypeScript uses ... :(
Anyways, thank you so much for allowing me to continue discussion with you
even after the interview and that the PR is closed.

If there is any other feedback you would like to provide me that would be
greatly appreciated!

P.S.
I have also updated my ecommerce project adding the resize eventListener
and learned about BEM and Monospace you introduced me to. Thanks for the
great resources! :)

Sincerely,
Joy

**Comment by caasi** [comment]
Hi @joy21fs, this is not an email. Take it easy.

You are right. Just change `{user.type}` to `{user._id}` fixes this problem.

If you want to know more, you can check other PRs:
- https://github.com/caasi/gd-frontend-202205/pull/2
- https://github.com/caasi/gd-frontend-202205/pull/3

Don't worry about TypeScript now. You can learn it after you're familiar with JavaScript.

I will check your ecommerce project later. You're awesome!

**Comment by joy21fs** [comment]
Thank you Isaac! (I initially thought since the PR was closed I was communicating with you through email exchanges :PP

I have been learning more about react hooks and their usages these days as well and have enjoyed reviewing the comments of other PRs, still trying to comprehend lots of the new knowledge and trying to make them my own before implementing them. 
I updated the README file on the forked repository, if that's ok with you, to document my process and what I learned. 
Thank you so much again for the time you spent for the discussions and offering me encouragement and feedback, they really meant a lot to me!

**Comment by caasi** [comment]
> I have been learning more about react hooks and their usages these days as well and have enjoyed reviewing the comments of other PRs, still trying to comprehend lots of the new knowledge and trying to make them my own before implementing them.

👍

> I updated the README file on the forked repository, if that's ok with you, to document my process and what I learned.
Thank you so much again for the time you spent for the discussions and offering me encouragement and feedback, they really meant a lot to me!

You can do whatever you want in your fork. That's the spirit of git. :D

**Pull request closed without merging**
